import pyfiglet
import random
import time

#baner
baner = pyfiglet.figlet_format("Bitco1ner")
print(baner)

print('Mine bitcoins easly with bitco1ner!')
id = input('Type your cryptowallet ID:')
print('Mining bitcoins and sending to: '+id)

print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(0.5)
print(random.getrandbits(64))
time.sleep(2)
print('Bitcoin mined:')
print(random.uniform(0, 1))
print('Enjoy! Now quitting Bitco1ner...')